title: Maverick Nguyen
logo: /assets/img/profile.jpg
description: |
  <strong>CONTACT</strong><br>
  <strong>Phone:</strong> <a href="tel:+1234567890">+123-456-7890</a><br>
  <strong>Email:</strong> <a href="mailto:your.email@example.com">your.email@example.com</a><br>
  <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/maverick-nguyen">Maverick Nguyen</a><br>
  <strong>GitHub:</strong> <a href="https://github.com/NguyenMav">NguyenMav</a><br><br>

show_downloads: false
theme: jekyll-theme-minimal
