title: Maverick Nguyen
logo: /assets/img/profile.png
description: |
  <strong>CONTACT</strong><br>
  <strong>Email:</strong> <a href="mailto:nguyenmav@deakin.edu.au">nguyenmav@deakin.edu.au</a><br>
  <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/maverick-nguyen">maverick-nguyen</a><br>
  <strong>Datacamp:</strong> <a href="https://www.datacamp.com/portfolio/maverick-nguyen">maverick-nguyen</a><br>
  <strong>GitHub:</strong> <a href="https://github.com/NguyenMav">NguyenMav</a><br><br>

  <strong>Languages:</strong><br>
  • English (Native)<br>
  • Vietnamese (Limited)<br><br>
  
  <strong>Interests and Hobbies:</strong><br>
  • Weightlifting and Bodybuilding<br>
  • Cooking and Baking<br>
  • Audiobooks and Novels<br>
  • PC/Mobile Gaming

show_downloads: false
theme: jekyll-theme-minimal
