title: Maverick Nguyen
logo: /assets/img/profile.jpg
description: |
  **CONTACT**

  **Phone:** [+123-456-7890](tel:+1234567890)  
  **Email:** [your.email@example.com](mailto:your.email@example.com)  
  **LinkedIn:** [Maverick Nguyen](https://linkedin.com/in/maverick-nguyen)  
  **GitHub:** [NguyenMav](https://github.com/NguyenMav)

show_downloads: false
theme: jekyll-theme-minimal
