title: Maverick Nguyen
logo: /assets/img/profile.jpg
description: |
  <strong>Phone:</strong> <a href="tel:+1234567890">+123-456-7890</a><br>
  <strong>Email:</strong> <a href="mailto:your.email@example.com">your.email@example.com</a><br>
  <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/maverick-nguyen">Maverick Nguyen</a><br>
  <strong>GitHub:</strong> <a href="https://github.com/NguyenMav">NguyenMav</a><br><br>

  <strong>EDUCATION</strong><br>
  <strong>Master in Data Science</strong><br>
  Deakin University<br>
  January 2024 - December 2025<br><br>

  <strong>Bachelor of Medical Imaging</strong><br>
  Deakin University<br>
  March 2020 - December 2023
show_downloads: false
theme: jekyll-theme-minimal
