title: Maverick Nguyen
logo: /assets/img/profile.jpg
description: |
  <strong>CONTACT</strong><br>
  <strong>Email:</strong> <a href="mailto:nguyenmav@deakin.edu.au">nguyenmav@deakin.edu.au</a><br>
  <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/maverick-nguyen">maverick-nguyen</a><br>
  <strong>GitHub:</strong> <a href="https://github.com/NguyenMav">NguyenMav</a><br><br>

show_downloads: false
theme: jekyll-theme-minimal
